### PR TITLE
Rename package name from io.airlift.slice to com.facebook.slice

### PR DESCRIPTION
**Pull request by wenleix**
Similar to the procedures in https://github.com/prestodb/drift/pull/2

Ready for review

### CODE REVIEW

**Comment by rschlussel** [comment]
do we still want packages to be com.facebook?

**Comment by wenleix** [comment]
@rschlussel : Since both Presto and Drift are still using package `com.facebook`, I will stay with `com.facebook` for now (until we agreed on a new package name :) )

**Review by mbasmanova — COMMENTED** [review]
@wenleix Perhaps, make commit title a bit more explanatory: `Rename package name from io.airlift.slice to com.facebook.slice`

**Review by mbasmanova — APPROVED** [review]
@wenleix Thanks.

**Review by highker — APPROVED** [review]
LGTM

**Review by arhimondr — APPROVED** [review]

**Comment by wenleix** [comment]
I click the GitHub button and the default behavior is merge. We should configure to always use rebase and push.

**Pull request merged**
